### ISSUE TITLE
bare-server-node not found

### ISSUE THREAD

**Issue by cactusflips2020** [mecharis-420/Kitty-Cat-Club#2]
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/bare-server-node/-/bare-server-node-2.0.0.tgz - Not found
npm error 404
npm error 404  'bare-server-node@https://registry.npmjs.org/bare-server-node/-/bare-server-node-2.0.0.tgz' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.

I'm trying to build and when npm install runs this error is given.

**Comment by cactusflips2020** [comment]
Problem solved: i figured it out.

**Comment by N-coder82** [comment]
CLOSE THE ISSUE

**Comment by N-coder82** [comment]
Thx
